In [18]:
import os
import json
from pathlib import Path
from functools import partial
from typing import List, Optional, Dict, Tuple

import numpy as np
import pandas as pd
import torch
import torch.nn as nn

from tqdm import tqdm

import seaborn as sns
import matplotlib.pyplot as plt

import pyro
from pyro.distributions import Normal, Uniform, Delta
from pyro.infer import SVI, Trace_ELBO
from pyro.optim import Adam
from pyro.distributions.util import logsumexp
from pyro.infer import EmpiricalMarginal, SVI, Trace_ELBO, TracePredictive
from pyro.infer.mcmc import MCMC, NUTS
import pyro.optim as optim
import pyro.poutine as poutine

# for CI testing
smoke_test = ('CI' in os.environ)
# assert pyro.__version__.startswith('0.3.1')
pyro.enable_validation(True)
pyro.set_rng_seed(1)
pyro.enable_validation(True)

In [ ]:
DATA_URL = "https://d2fefpcigoriu7.cloudfront.net/datasets/rugged_data.csv"
data = pd.read_csv(DATA_URL, encoding="ISO-8859-1")
df = data[["cont_africa", "rugged", "rgdppc_2000"]]
df = df[np.isfinite(df.rgdppc_2000)]
df["rgdppc_2000"] = np.log(df["rgdppc_2000"])

In [ ]:
df.info()

In [ ]:
sns.distplot(df["rugged"])

In [ ]:
class OLS(nn.Module):
    def __init__(self, num_params):
        super(OLS, self).__init__()
        self.linear = nn.Linear(num_params, 1)
        
    def forward(self, x):
        return self.linear(x)

In [ ]:
model = OLS(3)

In [ ]:
x_data = torch.rand(1000, 3)

In [ ]:
y_data = x_data @ torch.tensor([[2],[-1], [1]], dtype=torch.float32) + torch.tensor(1e-2)

In [ ]:
loss_fn = torch.nn.MSELoss(reduction='sum')
optim = torch.optim.Adam(model.parameters(), lr=0.1)
num_iterations = 1000


def main():
    for j in range(num_iterations):
        # run the model forward on the data
        y_pred = model(x_data).squeeze(-1)
        # calculate the mse loss
        loss = loss_fn(y_pred, y_data)
        # initialize gradients to zero
        optim.zero_grad()
        # backpropagate
        loss.backward()
        # take a gradient step
        optim.step()
        if (j + 1) % 50 == 0:
            print("[iteration %04d] loss: %.4f" % (j + 1, loss.item()))
    # Inspect learned parameters
    print("Learned parameters:")
    for name, param in model.named_parameters():
        print(name, param.data.numpy())

main()

In [ ]:
## Bayesian Regression

In [ ]:
def model(x_data, y_data):
    # weight and bias priors
    w_prior = Normal(torch.zeros(1, 2), torch.ones(1, 2)).to_event(1)
    b_prior = Normal(torch.tensor([[8.]]), torch.tensor([[1000.]])).to_event(1)
    f_prior = Normal(0., 1.)
    priors = {'linear.weight': w_prior, 'linear.bias': b_prior, 'factor': f_prior}
    scale = pyro.sample("sigma", Uniform(0., 10.))
    # lift module parameters to random variables sampled from the priors
    lifted_module = pyro.random_module("module", regression_model, priors)
    # sample a nn (which also samples w and b)
    lifted_reg_model = lifted_module()
    with pyro.plate("map", len(x_data)):
        # run the nn forward on data
        prediction_mean = lifted_reg_model(x_data).squeeze(-1)
        # condition on the observed data
        pyro.sample("obs",
                    Normal(prediction_mean, scale),
                    obs=y_data)
        return prediction_mean

In [ ]:
from pyro.contrib.autoguide import AutoDiagonalNormal
guide = AutoDiagonalNormal(model)

In [ ]:
optim = Adam({"lr": 0.03})
svi = SVI(model, guide, optim, loss=Trace_ELBO(), num_samples=1000)

In [ ]:
def train():
    pyro.clear_param_store()
    for j in range(num_iterations):
        # calculate the loss and take a gradient step
        loss = svi.step(x_data, y_data)
        if j % 100 == 0:
            print("[iteration %04d] loss: %.4f" % (j + 1, loss / len(data)))

train()

In [ ]:
for name, value in pyro.get_param_store().items():
    print(name, pyro.param(name))

In [ ]:
get_marginal = lambda traces, sites:EmpiricalMarginal(traces, sites)._get_samples_and_weights()[0].detach().cpu().numpy()

def summary(traces, sites):
    marginal = get_marginal(traces, sites)
    site_stats = {}
    for i in range(marginal.shape[1]):
        site_name = sites[i]
        marginal_site = pd.DataFrame(marginal[:, i]).transpose()
        describe = partial(pd.Series.describe, percentiles=[.05, 0.25, 0.5, 0.75, 0.95])
        site_stats[site_name] = marginal_site.apply(describe, axis=1) \
            [["mean", "std", "5%", "25%", "50%", "75%", "95%"]]
    return site_stats

def wrapped_model(x_data, y_data):
    pyro.sample("prediction", Delta(model(x_data, y_data)))

posterior = svi.run(x_data, y_data)


In [ ]:
# posterior predictive distribution we can get samples from
trace_pred = TracePredictive(wrapped_model,
                             posterior,
                             num_samples=1000)
post_pred = trace_pred.run(x_data, None)
post_summary = summary(post_pred, sites= ['prediction', 'obs'])
mu = post_summary["prediction"]
y = post_summary["obs"]
predictions = pd.DataFrame({
    "cont_africa": x_data[:, 0],
    "rugged": x_data[:, 1],
    "mu_mean": mu["mean"],
    "mu_perc_5": mu["5%"],
    "mu_perc_95": mu["95%"],
    "y_mean": y["mean"],
    "y_perc_5": y["5%"],
    "y_perc_95": y["95%"],
    "true_gdp": y_data,
})

In [ ]:
fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(12, 6), sharey=True)
african_nations = predictions[predictions["cont_africa"] == 1]
non_african_nations = predictions[predictions["cont_africa"] == 0]
african_nations = african_nations.sort_values(by=["rugged"])
non_african_nations = non_african_nations.sort_values(by=["rugged"])
fig.suptitle("Regression line 90% CI", fontsize=16)
ax[0].plot(non_african_nations["rugged"],
           non_african_nations["mu_mean"])
ax[0].fill_between(non_african_nations["rugged"],
                   non_african_nations["mu_perc_5"],
                   non_african_nations["mu_perc_95"],
                   alpha=0.5)
ax[0].plot(non_african_nations["rugged"],
           non_african_nations["true_gdp"],
           "o")
ax[0].set(xlabel="Terrain Ruggedness Index",
          ylabel="log GDP (2000)",
          title="Non African Nations")
idx = np.argsort(african_nations["rugged"])
ax[1].plot(african_nations["rugged"],
           african_nations["mu_mean"])
ax[1].fill_between(african_nations["rugged"],
                   african_nations["mu_perc_5"],
                   african_nations["mu_perc_95"],
                   alpha=0.5)
ax[1].plot(african_nations["rugged"],
           african_nations["true_gdp"],
           "o")
ax[1].set(xlabel="Terrain Ruggedness Index",
          ylabel="log GDP (2000)",
          title="African Nations")

In [ ]:
fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(12, 6), sharey=True)
fig.suptitle("Posterior predictive distribution with 90% CI", fontsize=16)
ax[0].plot(non_african_nations["rugged"],
           non_african_nations["y_mean"])
ax[0].fill_between(non_african_nations["rugged"],
                   non_african_nations["y_perc_5"],
                   non_african_nations["y_perc_95"],
                   alpha=0.5)
ax[0].plot(non_african_nations["rugged"],
           non_african_nations["true_gdp"],
           "o")
ax[0].set(xlabel="Terrain Ruggedness Index",
          ylabel="log GDP (2000)",
          title="Non African Nations")
idx = np.argsort(african_nations["rugged"])

ax[1].plot(african_nations["rugged"],
           african_nations["y_mean"])
ax[1].fill_between(african_nations["rugged"],
                   african_nations["y_perc_5"],
                   african_nations["y_perc_95"],
                   alpha=0.5)
ax[1].plot(african_nations["rugged"],
           african_nations["true_gdp"],
           "o")
ax[1].set(xlabel="Terrain Ruggedness Index",
          ylabel="log GDP (2000)",
          title="African Nations")

In [ ]:
# we need to prepend `module$$$` to all parameters of nn.Modules since
# that is how they are stored in the ParamStore
weight = get_marginal(posterior, ['module$$$linear.weight']).squeeze(1).squeeze(1)
factor = get_marginal(posterior, ['module$$$factor'])
gamma_within_africa = weight[:, 1] + factor.squeeze(1)
gamma_outside_africa = weight[:, 1]
fig = plt.figure(figsize=(10, 6))
sns.distplot(gamma_within_africa, kde_kws={"label": "African nations"},)
sns.distplot(gamma_outside_africa, kde_kws={"label": "Non-African nations"})
fig.suptitle("Density of Slope : log(GDP) vs. Terrain Ruggedness", fontsize=16)

In [416]:
def prepare_sequence(seq, to_ix):
    idxs = [to_ix[w] for w in seq]
    return torch.tensor(idxs, dtype=torch.long)

In [417]:
def argmax(vec):
    # return the argmax as a python int
    _, idx = torch.max(vec, 1)
    return idx.item()

In [418]:
# Compute log sum exp in a numerically stable way for the forward algorithm
def log_sum_exp(vec):
    max_score = vec[0, argmax(vec)]
    max_score_broadcast = max_score.view(1, -1).expand(1, vec.size()[1])
    return max_score + \
        torch.log(torch.sum(torch.exp(vec - max_score_broadcast)))

In [536]:
# taken from PyTorch tutorials: https://pytorch.org/tutorials/beginner/nlp/advanced_tutorial.html
class BiLSTM_CRF(nn.Module):

    def __init__(self, vocab_size, tag_to_ix, embedding_dim, hidden_dim):
        super(BiLSTM_CRF, self).__init__()

        self.embedding_dim = embedding_dim
        self.hidden_dim = hidden_dim
        self.vocab_size = vocab_size
        self.tag_to_ix = tag_to_ix
        # tagset_size includes <START> and <STOP>
        self.tagset_size = len(tag_to_ix)

        # embedding matrix
        self.word_embeds = nn.Embedding(vocab_size, embedding_dim)

        self.lstm = nn.LSTM(embedding_dim, hidden_dim // 2,
                            num_layers=1, bidirectional=True)

        # project the output of the LSTM at each state into tag space. Input to CRF model.
        # fully connected layers, emission score per token
        self.hidden2tag = nn.Linear(hidden_dim, self.tagset_size)

        # Matrix of transition parameters. Entry i,j is the score of
        # transitioning *to* i *from* j.
        self.transitions = nn.Parameter(
            torch.randn(self.tagset_size, self.tagset_size))

        # These two statements enforce the constraint that we never transfer
        # to the start tag and we never transfer from the stop tag
        self.transitions.data[tag_to_ix[START_TAG], :] = -10000
        self.transitions.data[:, tag_to_ix[STOP_TAG]] = -10000

        # this is NOT a right stochastic matrix whose row sums to 1, simply scores.

        self.hidden = self.init_hidden()

    def init_hidden(self):
        return (torch.randn(2, 1, self.hidden_dim // 2),
                torch.randn(2, 1, self.hidden_dim // 2))

    def _forward_alg(self, feats):
        # Do the forward algorithm to compute the partition function
        init_alphas = torch.full((1, self.tagset_size), -10000.)
        # START_TAG has all of the score.
        init_alphas[0][self.tag_to_ix[START_TAG]] = 0.

        # Wrap in a variable so that we will get automatic backprop
        forward_var = init_alphas

        # Iterate through the sentence
        for feat in feats:
            alphas_t = []  # The forward tensors at this timestep
            for next_tag in range(self.tagset_size):
                # broadcast the emission score: it is the same regardless of
                # the previous tag
                emit_score = feat[next_tag].view(
                    1, -1).expand(1, self.tagset_size)
                # the ith entry of trans_score is the score of transitioning to
                # next_tag from i
                trans_score = self.transitions[next_tag].view(1, -1)
                # The ith entry of next_tag_var is the value for the
                # edge (i -> next_tag) before we do log-sum-exp
                next_tag_var = forward_var + trans_score + emit_score
                # The forward variable for this tag is log-sum-exp of all the
                # scores.
                alphas_t.append(log_sum_exp(next_tag_var).view(1))
            forward_var = torch.cat(alphas_t).view(1, -1)
        terminal_var = forward_var + self.transitions[self.tag_to_ix[STOP_TAG]]
        alpha = log_sum_exp(terminal_var)
        return alpha

    def _penalty(self, lda=1e-2, norm="l1"):
        w = self.transitions.detach()
        w[tag_to_ix[START_TAG], :] = 0
        w[:, tag_to_ix[STOP_TAG]] = 0
        
        if norm == "l1":
            return w.abs().sum() * lda
        elif norm == "l2":
            return torch.pow(w, 2).sum().sqrt() * lda
        else:
            return 0

    def _get_lstm_features(self, sentence):
        self.hidden = self.init_hidden()
        embeds = self.word_embeds(sentence).view(len(sentence), 1, -1)
        lstm_out, self.hidden = self.lstm(embeds, self.hidden)
        lstm_out = lstm_out.view(len(sentence), self.hidden_dim)
        # output [len(sentences), hidden_dim]
        lstm_feats = self.hidden2tag(lstm_out)
        # lstm_feats [len(sentence), len(tag_size)] aka emission score
        return lstm_feats

    def _score_sentence(self, feats, tags):
        # feats in shape [len(sentences), len(tag_size)]
        # Gives the score of a provided tag sequence
        score = torch.zeros(1)
        # insert corresponding index of START_TAG
        tags = torch.cat([torch.tensor([self.tag_to_ix[START_TAG]], dtype=torch.long), tags])
        for i, feat in enumerate(feats):
            # feat in [hidden_size], emission score from LSTM
            score += self.transitions[tags[i + 1], tags[i]] + feat[tags[i + 1]]
        score += self.transitions[self.tag_to_ix[STOP_TAG], tags[-1]]
        # total of emission score and transition score, given the sequence and state transitions.
        return score

    def _viterbi_decode(self, feats):
        backpointers = []

        # Initialize the viterbi variables in log space
        init_vvars = torch.full((1, self.tagset_size), -10000.)
        init_vvars[0][self.tag_to_ix[START_TAG]] = 0

        # forward_var at step i holds the viterbi variables for step i-1
        forward_var = init_vvars
        for feat in feats:
            bptrs_t = []  # holds the backpointers for this step
            viterbivars_t = []  # holds the viterbi variables for this step

            for next_tag in range(self.tagset_size):
                # next_tag_var[i] holds the viterbi variable for tag i at the
                # previous step, plus the score of transitioning
                # from tag i to next_tag.
                # We don't include the emission scores here because the max
                # does not depend on them (we add them in below)
                next_tag_var = forward_var + self.transitions[next_tag]
                best_tag_id = argmax(next_tag_var)
                bptrs_t.append(best_tag_id)
                viterbivars_t.append(next_tag_var[0][best_tag_id].view(1))
            # Now add in the emission scores, and assign forward_var to the set
            # of viterbi variables we just computed
            forward_var = (torch.cat(viterbivars_t) + feat).view(1, -1)
            backpointers.append(bptrs_t)

        # Transition to STOP_TAG
        terminal_var = forward_var + self.transitions[self.tag_to_ix[STOP_TAG]]
        best_tag_id = argmax(terminal_var)
        path_score = terminal_var[0][best_tag_id]

        # Follow the back pointers to decode the best ptranath.
        best_path = [best_tag_id]
        for bptrs_t in reversed(backpointers):
            best_tag_id = bptrs_t[best_tag_id]
            best_path.append(best_tag_id)
        # Pop off the start tag (we dont want to return that to the caller)
        start = best_path.pop()
        assert start == self.tag_to_ix[START_TAG]  # Sanity check
        best_path.reverse()
        return path_score, best_path

    def neg_log_likelihood(self, sentence, tags):
        # Lafferty et al. 2001
        # sentences are index-of-vocabulary, so are tags
        feats = self._get_lstm_features(sentence)
        # feats [len(sentence), len(tag_size)]
        # probability of the sequence given parameters (of BiLSTM and CRF)
        forward_score = self._forward_alg(feats)
        # if states (i.e. tags) are given, probability of sequence (i.e. pure emission scores)
        gold_score = self._score_sentence(feats, tags)
        return forward_score - gold_score + self._penalty()

    def forward(self, sentence):  # dont confuse this with _forward_alg above.
        # Get the emission scores from the BiLSTM
        lstm_feats = self._get_lstm_features(sentence)

        # Find the best path, given the features.
        score, tag_seq = self._viterbi_decode(lstm_feats)
        return score, tag_seq

In [537]:
def jsonl_to_bilou(iterable: List[Dict]) -> Tuple:
    for i in iterable:
        tokens = i["paragraphs"][0]["sentences"][0]["tokens"]
        words = [token["orth"] for token in tokens]
        entities = [token["ner"] for token in tokens]
        yield tuple([words, entities])

In [487]:
START_TAG = "<START>"
STOP_TAG = "<STOP>"
EMBEDDING_DIM = 10
HIDDEN_DIM = 8

# Make up some training data
# training_data = [(
#     "the wall street journal reported today that apple corporation made money".split(),
#     "B I I I O O O B I O O".split()
# ), (
#     "georgia tech is a university in georgia".split(),
#     "B I O O O O B".split()
# )]

with open(Path("./data/onto.jsonl/onto.train.json"), "r") as f:
    raw_train_json = json.load(f)
    training_data = list(jsonl_to_bilou(raw_train_json))[:50]

# with open(Path("./data/onto.jsonl/onto.development.json"), "r") as f:
#     raw_dev_json = json.load(f)
#     validation_data = list(jsonl_to_bilou(raw_dev_json))

word_to_ix = {}
tag_to_ix = {}
for sentence, tags in training_data:
    for word in sentence:
        if word not in word_to_ix:
            word_to_ix[word] = len(word_to_ix)
    for tag in tags:
        if tag not in tag_to_ix:
            tag_to_ix[tag] = len(tag_to_ix)

# for sentence, tags in validation_data:
#     for word in sentence:
#         if word not in word_to_ix:
#             word_to_ix[word] = len(word_to_ix)
#     for tag in tags:
#         if tag not in tag_to_ix:
#             tag_to_ix[tag] = len(tag_to_ix)

tag_to_ix[START_TAG] = len(tag_to_ix)
tag_to_ix[STOP_TAG] = len(tag_to_ix)


In [488]:
model = BiLSTM_CRF(len(word_to_ix), tag_to_ix, EMBEDDING_DIM, HIDDEN_DIM)
optimizer = torch.optim.SGD(model.parameters(), lr=0.1, weight_decay=1e-4)

In [489]:
# Check predictions before training
with torch.no_grad():
    precheck_sent = prepare_sequence(training_data[0][0], word_to_ix)
    precheck_tags = torch.tensor([tag_to_ix[t] for t in training_data[0][1]], dtype=torch.long)
    print(model(precheck_sent))
    print(prepare_sequence(training_data[0][1], tag_to_ix))

(tensor(9.7741), [1, 25, 5, 18])
tensor([0, 0, 0, 0])


In [490]:
for epoch in range(30):
    for k, (sentence, tags) in enumerate(training_data):
        model.zero_grad()

        sentence_in = prepare_sequence(sentence, word_to_ix)
        targets = prepare_sequence(tags, tag_to_ix)

        loss = model.neg_log_likelihood(sentence_in, targets)

        loss.backward()
        optimizer.step()

In [491]:
tag_to_ix

{'O': 0,
 'B-DATE': 1,
 'L-DATE': 2,
 'B-MONEY': 3,
 'I-MONEY': 4,
 'L-MONEY': 5,
 'U-WORK_OF_ART': 6,
 'U-CARDINAL': 7,
 'B-ORG': 8,
 'I-ORG': 9,
 'L-ORG': 10,
 'U-ORG': 11,
 'B-PERSON': 12,
 'L-PERSON': 13,
 'U-GPE': 14,
 'I-DATE': 15,
 'U-PERSON': 16,
 'U-DATE': 17,
 'U-NORP': 18,
 'B-PERCENT': 19,
 'L-PERCENT': 20,
 'B-CARDINAL': 21,
 'I-CARDINAL': 22,
 'L-CARDINAL': 23,
 'I-PERSON': 24,
 'B-WORK_OF_ART': 25,
 'I-WORK_OF_ART': 26,
 'L-WORK_OF_ART': 27,
 '<START>': 28,
 '<STOP>': 29}

In [492]:
# Check predictions after training
with torch.no_grad():
    for i in range(len(training_data)):
        precheck_sent = prepare_sequence(training_data[i][0], word_to_ix)
        print(model(precheck_sent))
        print(prepare_sequence(training_data[i][1], tag_to_ix))

(tensor(53.2958), [0, 0, 0, 0])
tensor([0, 0, 0, 0])
(tensor(278.9512), [0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
(tensor(432.3887), [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0])
(tensor(500.3239), [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 6, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 6, 0, 6, 0, 0, 0])
(tensor(661.3035), [0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 9, 10, 0, 11, 0, 0, 8, 9, 10, 0])
tensor([ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  8,
         9, 10,

(tensor(817.7294), [0, 0, 0, 0, 0, 0, 14, 0, 8, 9, 9, 10, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 0, 0, 8, 9, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([ 0,  0,  0,  0,  0,  0, 14,  0,  8,  9,  9, 10,  0, 11,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0, 14,  0,  0,  0,  0,  0,  8,  9, 10,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0])
(tensor(578.1830), [11, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 12, 24, 24, 13, 0])
tensor([11,  0,  0,  0,  0,  0,  0,  0, 14,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11,  0,  0,  0, 12,
        24, 24, 13,  0])
(tensor(59.9662), [0, 0, 0, 0])
tensor([0, 0, 0, 0])
(tensor(366.2035), [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [493]:
penalty = model.transitions.data.numpy()

In [496]:
from flair.embeddings import WordEmbeddings

In [497]:
embedding = WordEmbeddings("glove")

/home/li/.virtualenvs/pp/lib/python3.6/site-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL


In [518]:
from flair.data import Sentence

In [519]:
test = "we are travelling to Washington ."

In [520]:
s = Sentence(test)

In [521]:
s[-2].get_embedding()

tensor([])

In [522]:
embedding.embed([s])

[Sentence: "we are travelling to Washington ." - 6 Tokens]

In [529]:
s[-2].get_embedding().size()

torch.Size([100])

In [535]:
torch.cat([token.get_embedding().unsqueeze(0) for token in s], 0).size()

torch.Size([6, 100])

In [757]:
with open("training.log", "r") as f:
    no_penalty_0 = f.readlines()

In [758]:
with open("training_1.log", "r") as f:
    no_penalty_1 = f.readlines()

In [759]:
with open("training_l1.log", "r") as f:
    l1_penalty_0 = f.readlines()

In [760]:
with open("training_l1_1.log", "r") as f:
    l1_penalty_1 = f.readlines()

In [761]:
with open("training_2.log", "r") as f:
    no_penalty_2 = f.readlines()

In [762]:
with open("training_l1_2.log", "r") as f:
    l1_penalty_2 = f.readlines()

In [772]:
with open("training_3.log", "r") as f:
    no_penalty_3 = f.readlines()

In [773]:
with open("training_l1_3.log", "r") as f:
    l1_penalty_3 = f.readlines()

In [783]:
with open("training_4.log", "r") as f:
    no_penalty_4 = f.readlines()

In [784]:
with open("training_l1_4.log", "r") as f:
    l1_penalty_4 = f.readlines()

In [811]:
with open("training_5.log", "r") as f:
    no_penalty_5 = f.readlines()

In [812]:
with open("training_l2_5.log", "r") as f:
    l2_penalty_5 = f.readlines()

In [813]:
def _get_scores(lines):
    _breaker = "MACRO_AVG: acc"
    CAP = False
    sep2 = " - "
    sep3 = ": "
    summary = {}
    for l in lines:
        if _breaker in l:
            CAP = True
            continue
        if CAP:
            try:
                sep1 = l.index("tp:")
            except ValueError:
                CAP = False
                continue
            l = l.strip()
            entity, rest = l[:sep1].strip(), l[sep1:]
            summary[entity] = dict([i.split(sep3) for i in rest.split(sep2)])

    return summary

In [814]:
p_objects = [i for i in locals() if "penalty" in i]

In [815]:
with_penalty = [i for i in p_objects if i.startswith("l") and "_penalty" in i]

In [816]:
without_penalty = [i for i in p_objects if "no_penalty" in i]

In [817]:
def assemble_results(penalty, no_penalty):
    p_lst = []
    no_p_lst = []

    for k, (p, no_p) in enumerate(zip(penalty, no_penalty)):
        
        p_df = _get_scores(eval(p))
        p_df = pd.DataFrame(p_df)
        p_df["EXPERIMENT"] = k
        p_df["PENALTY"] = True
        p_lst.append(p_df)
        
        df = _get_scores(eval(no_p))
        df = pd.DataFrame(df)
        df["EXPERIMENT"] = k
        df["PENALTY"] = False
        no_p_lst.append(df)

    rv = pd.concat(p_lst + no_p_lst)
    rv = rv.drop(rv.index.difference(["f1-score"]), axis=0).reset_index(drop=True)
    return rv

In [819]:
with_penalty

['l1_penalty_0',
 'l1_penalty_1',
 'l1_penalty_2',
 'l1_penalty_3',
 'l1_penalty_4',
 'l2_penalty_5']

In [820]:
without_penalty

['no_penalty_0',
 'no_penalty_1',
 'no_penalty_2',
 'no_penalty_3',
 'no_penalty_4',
 'no_penalty_5']

In [818]:
assm_df = assemble_results(with_penalty, without_penalty)

In [821]:
assm_df

CARDINAL    DATE   EVENT     FAC     GPE LANGUAGE     LAW     LOC   MONEY  \
0    0.4950  0.6825  0.1128  0.0000  0.7984   0.0000  0.0000  0.0082  0.6287   
1    0.5162  0.5973  0.0000  0.0000  0.7990   0.0000  0.0000  0.1643  0.5879   
2    0.5604  0.7133  0.0899  0.0000  0.8073   0.0000  0.0000  0.3524  0.7018   
3    0.5588  0.6828  0.0000  0.0382  0.7730   0.0000  0.0000  0.0000  0.6962   
4    0.6242  0.6913  0.0619  0.2571  0.7754   0.0000  0.0000  0.2541  0.6935   
5    0.6141  0.6378  0.1560  0.1215  0.7754   0.0000  0.0000  0.3393  0.7059   
6    0.4755  0.6363  0.0488  0.0000  0.8071   0.0000  0.0000  0.0000  0.6679   
7    0.5275  0.7008  0.0000  0.0000  0.8091   0.0000  0.0000  0.1162  0.5886   
8    0.6080  0.6870  0.1064  0.0000  0.7951   0.0000  0.0000  0.3497  0.7218   
9    0.5664  0.6919  0.0213  0.2027  0.7715   0.0000  0.0000  0.1711  0.7112   
10   0.6337  0.6758  0.0577  0.2157  0.7868   0.0000  0.0000  0.3018  0.7112   
11   0.6076  0.6454  0.1587  0.1318  0.7845   0.0000  0.0000  0.3044  0.7260   

      NORP ORDINAL     ORG PERCENT  PERSON PRODUCT QUANTITY    TIME  \
0   0.7698  0.1984  0.6450  0.7556  0.7976  0.0000   0.0000  0.0113   
1   0.7663  0.5079  0.5439  0.8020  0.7468  0.0000   0.2444  0.1765   
2   0.7757  0.5957  0.6860  0.7589  0.7950  0.1356   0.2683  0.0705   
3   0.7387  0.0000  0.6685  0.6452  0.7497  0.0000   0.0000  0.0000   
4   0.7649  0.5984  0.6606  0.7792  0.7799  0.0310   0.2338  0.1333   
5   0.7631  0.4411  0.6443  0.8081  0.7566  0.1406   0.1405  0.1904   
6   0.7595  0.2815  0.6657  0.7536  0.8134  0.0000   0.1009  0.0113   
7   0.7938  0.5309  0.6644  0.8081  0.7754  0.0000   0.2637  0.1525   
8   0.7711  0.5191  0.6938  0.7241  0.7847  0.0480   0.2534  0.1098   
9   0.7622  0.5622  0.6433  0.7360  0.7277  0.0576   0.2966  0.1818   
10  0.7588  0.6206  0.6640  0.7848  0.7794  0.0476   0.2731  0.1872   
11  0.7516  0.4000  0.6412  0.7944  0.7599  0.1151   0.1600  0.1981   

   WORK_OF_ART  EXPERIMENT  PENALTY  
0       0.0946           0     True  
1       0.0412           1     True  
2       0.0787           2     True  
3       0.1160           3     True  
4       0.0811           4     True  
5       0.2076           5     True  
6       0.0400           0    False  
7       0.1201           1    False  
8       0.0880           2    False  
9       0.1274           3    False  
10      0.1288           4    False  
11      0.2028           5    False